// Generated by CoffeeScript 1.3.3
(function() {
  var clearSquare, drawLine, drawSquare, i, mouseDown, moveLine, theLine;

  theLine = (function() {
    var _i, _results;
    _results = [];
    for (i = _i = 1; _i <= 30; i = ++_i) {
      _results.push(0);
    }
    return _results;
  })();

  drawSquare = function(x) {
    var canvas, ctx;
    canvas = $('#theline')[0];
    if (canvas.getContext) {
      ctx = canvas.getContext('2d');
      return ctx.fillRect(x, 0, x + 5, 5);
    }
  };

  clearSquare = function(x) {
    var canvas, ctx;
    canvas = $('#theline')[0];
    if (canvas.getContext) {
      ctx = canvas.getContext('2d');
      return ctx.clearRect(x, 0, x + 5, 5);
    }
  };

  drawLine = function() {
    var each, x, _i, _len, _results;
    x = 0;
    _results = [];
    for (_i = 0, _len = theLine.length; _i < _len; _i++) {
      each = theLine[_i];
      x += 5;
      if (each === 1) {
        _results.push(drawSquare(x));
      } else {
        _results.push(clearSquare(x));
      }
    }
    return _results;
  };

  setInterval(drawLine, 100);

  mouseDown = false;

  moveLine = function() {
    var newLine, _i;
    newLine = [];
    if (mouseDown) {
      newLine.push(1);
    } else {
      newLine.push(0);
    }
    for (i = _i = 0; _i <= 28; i = ++_i) {
      newLine.push(theLine[i]);
    }
    return theLine = newLine;
  };

  setInterval(moveLine, 100);

  $(function() {
    $('#button').mousedown(function() {
      return mouseDown = true;
    });
    return $('#button').mouseup(function() {
      return mouseDown = false;
    });
  });

}).call(this);
